SistemaDeReservas_PF/Controllers/ProyectoController.cs
using Newtonsoft.Json;
using RabbitMQ.Client;
using RabbitMQ.Client.Events;
using ReservaEntidades;
using SistemaDeReservas_PF.Properties;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SistemaDeReservas_PF.Controllers
{
    public class ProyectoController : Controller
    {
        // GET: Proyecto
        public ActionResult Reserva()
        {
            return View();
        }
        public ActionResult Promocion()
        {

            return View();
        }
        public ActionResult Viaje()
        {
            return View();
        }
        public ActionResult FullDayDetalles(int Pk_FullDayPromocion=0 ,int Pk_ViajesProgramados=0 )
        {
            Estructura_Promocion_FullDay full = new Estructura_Promocion_FullDay();
            if (Pk_FullDayPromocion !=0 )
            {
                
                using (ServiceFullDay.ServiceSoap_FullDayClient c = new ServiceFullDay.ServiceSoap_FullDayClient())
                {
                    full = c.obtenerPromocionFullDayPorId(Pk_FullDayPromocion);
                }
                               
                Session["Pk_FullDayPromocion"] = Pk_FullDayPromocion;
                Session["pk_FullDayPromagado"] = 0;
                double precio = 0;
                if (full.data != null)
                {
                    precio = full.data.Precio;
                    if (!string.IsNullOrEmpty(full.data.tipoPromocion))
                    {
                        full.data.tipoPromocion = " - " + full.data.tipoPromocion;
                    }
                    
                }
                Session["PrecioUnitario"] = precio;
                
            }
            else
            {
                Session["Pk_FullDayPromocion"] = 0;
                ViajesProgramados_FullDay vProg = new ViajesProgramados_FullDay();
                using (ServiceFullDay.ServiceSoap_FullDayClient cs = new ServiceFullDay.ServiceSoap_FullDayClient())
                {
                    Estructura_ViajesProgramados_FullDay rr = cs.obtenerViajeProgramadosFullDay(Pk_ViajesProgramados);
                    vProg = rr.data;
                }
                Promocion_FullDay pp = new Promocion_FullDay();
                pp.Cupos = vProg.cupos;
                pp.ruta = vProg.Ruta;
                pp.Precio = vProg.Precio;
                pp.fecha_valida = "";
                pp.rutaImagen = vProg.rutaImagen;
                pp.Descripcion = "Información de fullday ";
                Session["PrecioUnitario"] = pp.Precio;
                full.data=pp;
                Session["pk_FullDayPromagado"] = vProg.Pk_ViajesProgramados_FullDay;
            }
            ViewBag.Promocion_FullDay = full.data;
            DateTime fecha = DateTime.MaxValue;
            if (!string.IsNullOrEmpty(full.data.fecha_valida))
            {
                string[] separar = full.data.fecha_valida.Split('/');
                fecha = new DateTime(int.Parse(separar[2]), int.Parse(separar[1]), int.Parse(separar[0]));
            }
            Session["FechaMaximaValida"] = fecha.ToString("yyyy-MM-dd");
            
            return View();
        }

        public ActionResult MensajeFinal(string mensajeError, int pK_ReservaGenerado)
        {
            ViewBag.mensaje = mensajeError;
            ViewBag.Pk_Reserva = pK_ReservaGenerado;
            return View();
        }
        public ActionResult PromocionViaje(int pk_promocionViaje)
        {
           
            ViewBag.Pk_PromocionViaje = pk_promocionViaje;
            return View();
        }
        public ActionResult ReservarFullDay()
        {
            if (Session["Pk_FullDayPromocion"]==null  || Session["pk_FullDayPromagado"]==null)
            {
                return RedirectToAction("FullDay");
            }
            int Pk_FullDayPromocion = int.Parse(Session["Pk_FullDayPromocion"].ToString());
            int pk_FullDayPromagado = int.Parse(Session["pk_FullDayPromagado"].ToString());
            ViewBag.FechaMaxima = Session["FechaMaximaValida"].ToString();
            if (Pk_FullDayPromocion != 0 || pk_FullDayPromagado!=0)
            {
                if (Pk_FullDayPromocion != 0)
                {
                    ViewBag.FechaViaje = true;
                }
                else
                {
                    ViewBag.FechaViaje = false;
                }
                return View();

            }

            else
            {
                return RedirectToAction("FullDay");
            }

        }

       
        [HttpPost]
        public ActionResult ReservarFullDay(ReservaFullDay newReservaFullDay)
        {
            
            double preciounitario= (double)Session["PrecioUnitario"];
            newReservaFullDay.precioUnitario = preciounitario;
            int Pk_FullDayPromocion = (int)Session["Pk_FullDayPromocion"];
            string mensajeError = string.Empty;

            int pk_origen =(int)Session["pk_origen"]  ;
            int  pk_destino= (int)Session["pk_destino"]  ;
           
            newReservaFullDay.Fk_Origen = pk_origen;
            newReservaFullDay.Fk_Destino = pk_destino;
            if (newReservaFullDay.Fecha_Viaje==DateTime.MinValue)
            {
                newReservaFullDay.Fecha_Viaje = (DateTime)Session["Fecha_Consultado"];
            }
           
            newReservaFullDay.Fecha_Generado = DateTime.Now;
            newReservaFullDay.Estado = "Registrado";
            newReservaFullDay.precioTotal = preciounitario * newReservaFullDay.cantidad;
            int pK_ReservaGenerado = 0;
            ViewBag.FechaMaxima = Session["FechaMaximaValida"].ToString();
            if (Pk_FullDayPromocion != 0)
            {
                ViewBag.FechaViaje = true;
            }
            else
            {
                ViewBag.FechaViaje = false;
            }
            if (newReservaFullDay.Dni_cliente.Length!=8)
            {
                ViewBag.ErrorMensaje = "Deben ser 8 numeros del dni";
                return View();
            }
            if (newReservaFullDay.Telefono.Length!=9)
            {
                ViewBag.ErrorMensaje = "Deben ser 9 numeros del celular";
                return View();
            }
            if (!newReservaFullDay.Telefono.StartsWith("9"))
            {
                ViewBag.ErrorMensaje = "El numero de celular es invalido debe iniciar con 9";
                return View();
            }

            bool validaciondni = false;//validacion DNI
            if (Settings.Default.ActivarValidacionDni)
            {
                using (HttpClient cliente = new HttpClient())
                {
                    System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

                    string ruta = string.Format("https://apiperu.dev/api/dni/{0}?api_token={1}", newReservaFullDay.Dni_cliente, Settings.Default.TokenConsultarDni);

                    var tarea = cliente.GetAsync(ruta);
                    tarea.Wait();

                    var tarea2 = tarea.Result.Content.ReadAsStringAsync();
                    tarea2.Wait();

                    string texto = tarea2.Result;
                    DNI dni= Newtonsoft.Json.JsonConvert.DeserializeObject<DNI>(texto);
                    if (dni!=null && dni.success )
                    {
                        validaciondni = true;
                    }
                    else
                    {
                        ViewBag.ErrorMensaje = "DNI: "+ dni.message;
                    }

                }
            }
            if (validaciondni==false)
            {
                return View();
            }



            using (ServiceFullDay.ServiceSoap_FullDayClient c = new ServiceFullDay.ServiceSoap_FullDayClient())
            {
                
               Estructura_Post_int insertado= c.RegistrarReservaFullDay(newReservaFullDay);
                if (insertado.codigo!="OK")
                {
                    mensajeError = insertado.mensaje;
                }
                
                pK_ReservaGenerado = insertado.data;
                if (pK_ReservaGenerado > 0)
                {
                    var factory = new ConnectionFactory()
                    {
                        HostName = Settings.Default.IpRabbitServer,
                        Port = 5672,
                        VirtualHost = "/",
                        UserName = "admin",
                        Password = "admin"
                    };
                    using (var conection = factory.CreateConnection())
                    {
                        using (var channel = conection.CreateModel())
                        {
                            channel.QueueDeclare("MensajeDeReserva", false, false, false, null);
                            var body = Encoding.UTF8.GetBytes("Su reserva se ha realizado correctamente con N° " + pK_ReservaGenerado);
                            channel.BasicPublish("", "MensajeDeReserva", null, body);

                        }
                    }
                }
                //Envio de mensaje de prueba 


            }
            return RedirectToAction("MensajeFinal",new { mensajeError,pK_ReservaGenerado });

            //return MensajeFinal(mensajeError, pK_ReservaGenerado);
        }
        public ActionResult FullDay()
        {
            return View();

        }
        public ActionResult Consultas()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult getDestino(string Pk_origen)
        {
            List<SelectListItem> listaDestino = new List<SelectListItem>();
            try
            {
                using (HttpClient cliente = new HttpClient())
                {

SistemaDeReservas_PF/Views/Proyecto/Consultas.cshtml
@{
    ViewBag.Title = "Consultas";

}
<head>
    <style type="text/css">

        input[type=number]::-webkit-inner-spin-button,
        input[type=number]::-webkit-outer-spin-button {
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
            margin: 0;
        }
    </style>
</head>
@using (Html.BeginForm())
{
    <body>
        <h3 style="text-align:center; color:dodgerblue  ">Realiza su consulta</h3>
        <div class="container">
            <p></p>
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-offset-5 col-md-5">
                        <div class="form-group">
                            Dni: <input class="" type="number" required="required" id="txtNumeroDni" />
                            <button type="button" class="btn btn-primary" id="btnBuscarConsultas">Buscar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
}


<div class="container">
    <p style=" height:10px;"></p>
    <h3 style="color:dodgerblue; " class="text-center">Resultados de la Busqueda</h3>
    <p id="lblResultadoRegistros" class="invisible" style="color:red; font-size:12px;">No existe registros </p>

    <div class="container col-md-12">
        <p></p>
        <table id="tablaResultadosConsulta" class="table table-striped table-bordered table-sm table-dark" cellspacing="0" width="100%">

            <tr>
                <th>Nro de Reserva </th>
                <th>Fecha generado</th>
                <th>Origen </th>
                <th>Destino</th>
                <th>Fecha de viaje</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Subtotal</th>
                <th>Estado</th>

            </tr>



        </table>


    </div>

</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


<script>
    document.getElementById("btnviaje").classList.remove("active");
    document.getElementById("btnpromocion").classList.remove("active");
    document.getElementById("btnfullday").classList.remove("active");
    document.getElementById("btnconsultaViajes").classList.add("active");
    document.getElementById("grupoFiltros").remove();
    document.getElementById("linksuperior").remove();

    $("#btnBuscarConsultas").click(function ()
    {
        var cID = $("#txtNumeroDni").val(); 
        if (cID=="" || cID.length!=8) {
             alert("Ingrese un numero de Dni valido " );
            return;
        }
        $.getJSON("/Proyecto/getReservasPorDni", { Dni: cID },
            function (data) {

                var contador = 0;
                     var tablla = document.getElementById('tablaResultadosConsulta');
                        while (tablla.rows.length > 1) {
                            tablla.deleteRow(1);
                        }     

                        var tblFullday = $("#tablaResultadosConsulta");  
   
                    $.each(data, function (index, item)
                    {
                         contador += 1
                        var tb5 = $("<tr></tr>");
                        tb5.html(
                            ("<td>" + item.Pk_Reserva_FullDay + "</td>")
                              + " " + ("<td>" + item.Fecha_Generado + "</td>")
                            + " " + ("<td>" + item.origen + "</td>")
                            + " " + ("<td>" + item.destino + "</td>")
                              + " " + ("<td>" + item.fecha_viaje + "</td>")
                            + " " + ("<td>" + item.precioUnitario + "</td>")
                                + " " + ("<td>" + item.cantidad + "</td>")
                            + " " + ("<td>" + item.precioTotal + "</td>")
                             + " " + ("<td>" + item.Estado + "</td>")
                          

                        );
                        tblFullday.append(tb5);

                    });

                    if (contador == 0) {
                         document.getElementById("lblResultadoRegistros").classList.remove("invisible");
                    }
                    else {
                         document.getElementById("lblResultadoRegistros").classList.add("invisible");
                    }
            
                         
         });

    });
</script>

SistemaDeReservas_PF/Views/Proyecto/FullDay.cshtml
@{
    ViewBag.Title = "FullDay";
}

<h2 class="text-center" style="color:dodgerblue">Promociones</h2>
<div class="container overflow-hidden">

    <p></p>
    <h3 id="lblSinResultadoFullDay" class="invisible" style="color:red; ">No se encontraron resultados</h3>
    <div id="contenedorFullDay">
        <div class="row gy-5">
            <div class="col-4">

            </div>
        </div>

    </div>
</div>
<p style="height:20px;"></p>
//Resultados de la Busqueda
<div class="container">
    <p style=" height:10px;"></p>
    <h3 style="color:dodgerblue; " class="text-center">Resultados de la Busqueda</h3>
    <p id="lblResultadoFullday" class="invisible" style="color:red; font-size:12px;">No existe viajes programados </p>

    <div class="container col-md-12">
        <p></p>
        <table id="tablaResultadosFullday" class="table table-striped table-bordered table-sm table-dark" cellspacing="0" width="100%">

            <tr>
                <th>Ruta </th>
                <th>Precio</th>
                <th>Cupos</th>
                <th>Opciones </th>

            </tr>



        </table>


    </div>

</div>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script>

    function Click_ViajesProgramados(ctl) {
            var sss = ctl.value;
           var convertido = JSON.parse(sss);

           location.href = "/Proyecto/FullDayDetalles?Pk_ViajesProgramados="+convertido.Pk_ViajesProgramados_FullDay;
       }
   
   $(document).ready(function () {

          
        function clickPromocionFullDay(pk_promocionFullDay) {
            
            location.href = "/Proyecto/FullDayDetalles?Pk_FullDayPromocion="+ pk_promocionFullDay;
            
       }
       

        function buscarPromociones() {
            var pk_origen = $("#cboOrigen").val();
            var pk_destino = $("#cboDestino").val();
            var FechaInico = document.getElementById("Fecha_Inicio").value; 
            $.getJSON("/Proyecto/getPromocionFullDay", { pk_origen: pk_origen, pk_destino: pk_destino, fecha: FechaInico },
                function (data)
            {
                    const myNode = document.getElementById("contenedorFullDay");
                    while (myNode.lastChild) {
                        myNode.lastChild.remove();
                    }
                    var contador = 0;
                    let li = document.createElement('div');
                    //li.id = "contenedorViajes"
                    let li2 = document.createElement('div');
                    li2.classList.add("row");
                    li2.classList.add("gy-5");
                    $.each(data, function (index, item) {
                        contador += 1
                        let li3 = document.createElement('div');
                        li3.classList.add("col-4");
                        let li4 = document.createElement('div');
                        li4.classList.add("p-3");
                        li4.classList.add("border");
                        li4.classList.add("bg-light");

                        let h33 = document.createElement("h3");
                        h33.classList.add("text-center");
                        h33.style.color = "Red";
                        h33.textContent = "Valido hasta: " + item.fecha_valida;
                        li4.appendChild(h33);

                        let img1 = document.createElement("img");
                        img1.width = 340;
                        img1.height = 150;
                        img1.src = item.rutaImagen;
                        li4.appendChild(img1);

                        let p1 = document.createElement("p");
                        li4.appendChild(p1);

                        
                        let p2 = document.createElement("p");
                        p2.style.fontSize = "16px";
                        p2.style.color = "dodgerblue";
                        p2.style.font = "bold";
                        p2.textContent = item.Descripcion;
                        
                        li4.appendChild(p2);
                        let h32 = document.createElement("h3");
                        h32.style.color = "Red";
                        h32.textContent = "S/ " + item.Precio + " - "+ item.tipoPromocion;
                        li4.appendChild(h32);

                      
                        let h3 = document.createElement("h3");
                        h3.classList.add("text-left");
                        h3.textContent = item.ruta;
                        li4.appendChild(h3);

                        let p3 = document.createElement("p");
                        p3.textContent = "Cupos limitados: " + item.Cupos;
                        li4.appendChild(p3);


                        let buttom1 = document.createElement("button");
                        buttom1.type = "submit";
                        buttom1.classList.add("btn");
                        buttom1.classList.add("btn-warning");
                        buttom1.value = item.Pk_Promocion_viaje;
                        buttom1.id = "btnReservarFullDay";
                        buttom1.textContent = "Mas detalles";
                        buttom1.style = "float:right";
                        buttom1.addEventListener("click", function () { clickPromocionFullDay(item.Pk_promocionFullDay) }, false);

                        li4.appendChild(buttom1);

                        li3.appendChild(li4);
                        li2.appendChild(li3);


                    });
                    if (contador > 0) {
                        li.appendChild(li2);                       
                        myNode.appendChild(li);
                    }
                    if (contador == 0) {
                        document.getElementById("lblSinResultadoFullDay").classList.remove("invisible");
                    }
                    else {
                        document.getElementById("lblSinResultadoFullDay").classList.add("invisible");
                    }
                });

           

            $.getJSON("/Proyecto/getViajesProgramadosFullDay", { pk_origen: pk_origen, pk_destino: pk_destino, fecha: FechaInico },
                function (data) {
                    var contador = 0;
                     var tablla = document.getElementById('tablaResultadosFullday');
                        while (tablla.rows.length > 1) {
                            tablla.deleteRow(1);
                        }     

                        var tblFullday = $("#tablaResultadosFullday");  
   
                    $.each(data, function (index, item)
                    {
                         contador += 1
                        var tb5 = $("<tr></tr>");
                        tb5.html(
                            ("<td>" + item.Ruta + "</td>")
                             
                            + " " + ("<td>" + item.Precio + "</td>")
                            + " " + ("<td>" + item.cupos + "</td>")
                            + "<td>" +  "<button type='button'  value='" + JSON.stringify(item) + "'  onclick='Click_ViajesProgramados(this);' class='btn btn-warning btn-sm '> Mas detalles " + "</button>" +
                            "</td>"

                        );
                        tblFullday.append(tb5);

                    });

                    if (contador == 0) {
                         document.getElementById("lblResultadoFullday").classList.remove("invisible");
                    }
                    else {
                         document.getElementById("lblResultadoFullday").classList.add("invisible");
                    }
                });
        }

        

        $("#btnBuscar").click(function () {

            buscarPromociones();
        });
        function sleep(time) {
            return new Promise((resolve) => setTimeout(resolve, time));
        }
        document.querySelector("#cboDestino").addEventListener("EventoSeleccion", (event) => {
            sleep(500).then(() => {
                buscarPromociones();
            });

        });

    document.getElementById("btnfullday").classList.add("active");
    document.getElementById("btnpromocion").classList.remove("active");
    document.getElementById("btnviaje").classList.remove("active");
    document.getElementById("btnconsultaViajes").classList.remove("active");

    });


</script>

SistemaDeReservas_PF/Views/Proyecto/MensajeFinal.cshtml
@{
    ViewBag.Title = "Reservar - FullDay exitosa";

}

    <body>
        <div class="container center-block col-md-offset-2">
            @if (ViewBag.Pk_Reserva == 0)
            {
                <p style="color:red; font-size:14px;">No se pudo realizar la reserva</p>
            }
            else
            {

                <p style="color:limegreen; font-size:16px;">Exito al generar la reserva N° @ViewBag.Pk_Reserva  </p>
                <p style="font-size:14px;" >Nuestros operadores se van a estar comunicando dentro de las 24 horas con usted para realizar el pago correspondiente de la reserva </p>
            }
            <div class="row">
                <div class="col-md-offset-4 col-md-2">
                    @Html.ActionLink("FullDay", "FullDay", "Proyecto", null, new { @class = "btn btn-info" })
                </div>
            </div>
          

        </div>
       

    </body>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {


        

        document.getElementById("linksuperior").remove();
        document.getElementById("grupoFiltros").remove();

    });



</script>

SistemaDeReservas_PF/Views/Proyecto/PromocionViaje.cshtml
@{
    ViewBag.Title = "Promocion Viaje ";
}

<head>

</head>
<body>
    <h3 class="text-center">Registra tu reserva de viaje </h3>
    <p></p>
    <div class="container">
        <div class="row">
            <p></p>
        </div>
        <div class="col-md-12" style="font-size:14px; ">
            <div class="row">
                <div class="offset-md-2 col-md-2">
                    <div class="form-group">
                        Nombre:
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <input type="text" id="txtnombre" style="width:100%;" required />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="offset-md-2 col-md-2">
                    <div class="form-group">
                        Apellido:
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <input type="text" id="txtapellido" style="width:100%;" required />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="offset-md-2 col-md-2">
                    <div class="form-group">
                        Dni:
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <input type="text" id="txtDni" style="width:100%;" required />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="offset-md-2 col-md-2">
                    <div class="form-group">
                        Telefono:
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <input type="text" id="txttelefono" style="width:100%;" required />
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="offset-md-2 col-md-2">
                    <div class="form-group">
                        Correo:
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <input type="text" id="txtcorreo" style="width:100%;" required />
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="offset-md-2 col-md-2">
                    <div class="form-group">
                        Fecha de viaje:
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <input type="date" id="txtFechaDeViaje" style="width:100%;" required />
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="offset-md-2 col-md-2">
                    <div class="form-group">
                        Asiento:
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <input type="text" id="txtasiento" style="width:100%;" required />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="offset-md-5 col-md-2">
                    <div class="form-group">
                        <button class="btn btn-primary" id="btnGuardar">Guardar</button>
                    </div>
                </div>
            </div>
        </div>

    </div>

</body>

<script>
    document.getElementById("linksuperior").remove();
    document.getElementById("grupoFiltros").remove();
    
</script>